# Generated by Django 3.2 on 2021-04-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarnLoviesOrBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('earn_or_buy', models.CharField(choices=[('EARN', 'Earn'), ('BUY', 'Buy')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_from', models.CharField(max_length=30)),
                ('payment_to', models.CharField(max_length=30)),
                ('payment_for', models.TextField(max_length=300)),
                ('amount_payed', models.IntegerField()),
                ('date_of_transaction', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
