# Generated by Django 3.2.4 on 2021-10-01 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_from', models.CharField(max_length=30)),
                ('payment_to', models.CharField(max_length=30)),
                ('payment_for', models.TextField(max_length=300)),
                ('amount_payed', models.IntegerField()),
                ('date_of_transaction', models.DateField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Transaction',
                'db_table': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Lovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lovie_bank', models.IntegerField(default=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EarnLoviesOrBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('earn_or_buy', models.CharField(choices=[('EARN', 'Earn'), ('BUY', 'Buy')], max_length=4)),
                ('completed', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Earn/Buy',
                'db_table': 'Earn/Buy Lovies',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentor', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('likes', models.IntegerField(default=0, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.transactions')),
            ],
            options={
                'verbose_name': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Boo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boo', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
