# Generated by Django 3.2 on 2021-04-23 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Transaction'},
        ),
        migrations.AlterModelTable(
            name='transactions',
            table='Transactions',
        ),
    ]
