# Generated by Django 3.2.4 on 2021-10-04 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_earnloviesorbuy_completed_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
    ]
