# Generated by Django 3.2 on 2021-04-23 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210422_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earnloviesorbuy',
            options={'verbose_name': 'Earn/Buy'},
        ),
        migrations.AlterModelTable(
            name='earnloviesorbuy',
            table='Earn/Buy Lovies',
        ),
    ]
