# Generated by Django 3.2 on 2021-06-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210614_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commentor',
            field=models.CharField(default='name', max_length=30),
            preserve_default=False,
        ),
    ]
