# Generated by Django 3.2.4 on 2021-07-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_boo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
