# Generated by Django 3.2.4 on 2021-07-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_comments_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnloviesorbuy',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
